name: grocio
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Define the version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1


  # Cupertino icons for iOS styling
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

flutter:
  # Material Icons are included by default
  uses-material-design: true

  # Add your app assets
  assets:
    - assets/logo.png
